### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by pazza2234** [tenacityteam/tenacity-flatpak-nightly#3]
i always get this error when installing
error: The application org.tenacityaudio.Tenacity/x86_64/nightly requires the runtime org.freedesktop.Platform/x86_64/21.08 which was not found

**Comment by TheEvilSkeleton** [comment]
Do you have the Flathub remote added?

**Comment by pazza2234** [comment]
???
idk all i know is i have pop os and did the commands that where in there for installation. no more then that

**Comment by pazza2234** [comment]
it is also a new(ish) install of it and i just need a audio edditor

**Comment by TheEvilSkeleton** [comment]
Did you read the instructions in the [README](https://github.com/tenacityteam/tenacity-flatpak-nightly/blob/main/README.md)?

**Comment by pazza2234** [comment]
-_- i icnored the "Make sure to have the Flathub remote added." sorry
