### ISSUE TITLE
Cannot Install on PopOs 22.04

### ISSUE THREAD

**Issue by therealayayron** [tenacityteam/tenacity-flatpak-nightly#4]
I am unable to install Tenacity and receive the following error:

error: The application org.tenacityaudio.Tenacity/x86_64/nightly requires the runtime org.freedesktop.Platform/x86_64/21.08 which was not found

1. Enter the following in Terminal:
flatpak remote-add tenacity oci+https://tenacityteam.github.io/tenacity-flatpak-nightly

2. Enter the following in Terminal:
flatpak install tenacity org.tenacityaudio.Tenacity

3. Error I receive: 
error: The application org.tenacityaudio.Tenacity/x86_64/nightly requires the runtime org.freedesktop.Platform/x86_64/21.08 which was not found

I was not able to install this application when I was on PopOS 21.08 either

I am currently on PopOS 22.04

This application was able to be installed on Kubuntu 22.04 and Fedora 36 and they work fine.

**Comment by TheEvilSkeleton** [comment]
Can you run `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo` and then try to install Tenacity?

**Comment by therealayayron** [comment]
@TheEvilSkeleton it's installing now. Much appreciated!

If any issues come up, I will notify you.

Would you happen to know when the official release will be dropping? 

I asked this on the official Reddit but it does not seem active anymore.

**Comment by TheEvilSkeleton** [comment]
Unfortunately the project is inactive. There's not much development going on anymore, so I cannot tell when a new version is coming out. Sorry.

**Comment by therealayayron** [comment]
Tenacity does not seem to be opening.

I do see a microphone in the upper right-hand corner of the menu (as if it's open and a microphone is attached).

But nothing opens. When I try to open Tenacity again by clicking on the icon (again), I get the following error:

An unrecoverable error has occurred during startup

**Comment by TheEvilSkeleton** [comment]
What happens when you run `flatpak run org.tenacityaudio.Tenacity`?

**Comment by therealayayron** [comment]
Still does not open. 

I the mic in the upper right-hand corner appears. 

In the command line, I see a vertical blinking bar as if something is loading. 

The bar eventually goes away but nothing loads and my terminal name reappears for me to type something in the terminal.

**Comment by TheEvilSkeleton** [comment]
Do you get any error in the terminal?

**Comment by therealayayron** [comment]
No error in the terminal

**Comment by TheEvilSkeleton** [comment]
I see, unfortunately I'm quite unfamiliar with the codebase so I cannot help you any further. Sorry.

**Comment by therealayayron** [comment]
No worries. Thank you for your help. I'll open another ticket
